# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "ko-KR"

reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_review:
      enabled: true
      auto_incremental_review: true
      base_branches:
        - main
        - dev
      review_status: true
  review_status: true
  commit_status: true
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
