spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  forward-headers-strategy: framework
