CREATE TABLE court_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    organizer_id BIGINT NOT NULL,
    grade_type VARCHAR(255) NOT NULL,
    game_type VARCHAR(255) NOT NULL,
    game_status VARCHAR(255) NOT NULL,
    match_record_mode VARCHAR(255) NOT NULL,
    share_code VARCHAR(64),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_court_games_organizer FOREIGN KEY (organizer_id)
        REFERENCES users(id)
);

CREATE TABLE court_game_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    user_id BIGINT,
    original_name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    grade VARCHAR(255) NOT NULL,
    age_group INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_court_game_participants_game FOREIGN KEY (game_id)
        REFERENCES court_games(id),
    CONSTRAINT fk_court_game_participants_user FOREIGN KEY (user_id)
        REFERENCES users(id),
    CONSTRAINT uq_court_game_participants_game_user UNIQUE (game_id, user_id)
);

CREATE TABLE court_game_managers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_court_game_managers_game FOREIGN KEY (game_id)
        REFERENCES court_games(id),
    CONSTRAINT fk_court_game_managers_user FOREIGN KEY (user_id)
        REFERENCES users(id),
    CONSTRAINT uq_court_game_managers_game_user UNIQUE (game_id, user_id)
);

CREATE TABLE court_free_game_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    court_count INTEGER NOT NULL,
    round_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_court_free_game_settings_game FOREIGN KEY (game_id)
        REFERENCES court_games(id),
    CONSTRAINT uq_court_free_game_settings_game UNIQUE (game_id)
);

CREATE TABLE court_free_game_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL,
    round_status VARCHAR(255),
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_court_free_game_rounds_game FOREIGN KEY (game_id)
        REFERENCES court_games(id),
    CONSTRAINT uq_court_free_game_rounds_game_round UNIQUE (game_id, round_number)
);

CREATE TABLE court_free_game_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL,
    court_number INTEGER NOT NULL,
    team_a_player1_id BIGINT,
    team_a_player2_id BIGINT,
    team_b_player1_id BIGINT,
    team_b_player2_id BIGINT,
    match_type VARCHAR(255),
    match_status VARCHAR(255),
    winner_team VARCHAR(255),
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_court_free_game_matches_round FOREIGN KEY (round_id)
        REFERENCES court_free_game_rounds(id),
    CONSTRAINT fk_court_free_game_matches_team_a_player1 FOREIGN KEY (team_a_player1_id)
        REFERENCES court_game_participants(id),
    CONSTRAINT fk_court_free_game_matches_team_a_player2 FOREIGN KEY (team_a_player2_id)
        REFERENCES court_game_participants(id),
    CONSTRAINT fk_court_free_game_matches_team_b_player1 FOREIGN KEY (team_b_player1_id)
        REFERENCES court_game_participants(id),
    CONSTRAINT fk_court_free_game_matches_team_b_player2 FOREIGN KEY (team_b_player2_id)
        REFERENCES court_game_participants(id),
    CONSTRAINT uq_court_free_game_matches_round_court UNIQUE (round_id, court_number)
);
